{{- $serviceValues := .Values.fileservice -}}
{{- $migrationsRunAsJob := dig "migrations" "runAsJob" false $serviceValues -}}
{{- $migrationsAutoCleanupSuccessfulJob := dig "migrations" "autoCleanupSuccessfulJob" true $serviceValues -}}
{{- $migrationsPodAnnotations := dig "migrations" "podAnnotations" dict $serviceValues -}}
{{- $migrationsPodLabels := dig "migrations" "podLabels" dict $serviceValues -}}
{{- $migrationsBackoffLimit := dig "migrations" "backoffLimit" 0 $serviceValues -}}
{{- if and $serviceValues.enabled $migrationsRunAsJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fileservice.fullname" . }}-db-migrate
  labels:
    {{- include "fileservice.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: {{ if $migrationsAutoCleanupSuccessfulJob }}before-hook-creation,hook-succeeded{{ else }}before-hook-creation{{ end }}
spec:
  backoffLimit: {{ $migrationsBackoffLimit | int }}
  template:
    metadata:
      labels:
        {{- include "fileservice.labels" . | nindent 8 }}
        {{- with $migrationsPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $migrationsPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "fileservice.fullname" . | quote }}
      {{- with $serviceValues.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.imagePullSecrets $serviceValues.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: db-migrate
        {{- with $serviceValues.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ printf "%s/%s:%s" $serviceValues.registry $serviceValues.image $serviceValues.tag | quote }}
        imagePullPolicy: {{ $serviceValues.imagePullPolicy | quote }}
        command:
        - "poetry"
        - "run"
        - "alembic"
        - "upgrade"
        - "head"
        {{- if or $serviceValues.secretName $serviceValues.extraEnvSecrets }}
        envFrom:
        {{- end }}
        {{- if $serviceValues.secretName }}
        - secretRef:
            name: {{ $serviceValues.secretName | quote }}
        {{- end }}
        {{- with $serviceValues.extraEnvSecrets }}
        {{- range . }}
        - secretRef:
            name: {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if or $serviceValues.env .Values.trustedCertBundle }}
        env:
        {{- with $serviceValues.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.trustedCertBundle }}
        - name: GRPC_DEFAULT_SSL_ROOTS_FILE_PATH
          value: /usr/lib/ssl/cert.pem
        - name: REQUESTS_CA_BUNDLE
          value: /usr/lib/ssl/cert.pem
        - name: SSL_CERT_DIR
          value: /usr/lib/ssl/certs
        - name: SSL_CERT_FILE
          value: /usr/lib/ssl/cert.pem
        {{- end }}
        {{- end }}
        {{- if or $serviceValues.volumeMounts .Values.trustedCertBundle }}
        volumeMounts:
        {{- with $serviceValues.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.trustedCertBundle }}
        - name: trusted-certs
          mountPath: /usr/lib/ssl/cert.pem
          subPath: bundle.crt
        {{- end }}
        {{- end }}
      {{- if or $serviceValues.volumes .Values.trustedCertBundle }}
      volumes:
      {{- with $serviceValues.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.trustedCertBundle }}
      - name: trusted-certs
        configMap:
          name: {{ include "shared.trustedCerts.name" . | quote }}
      {{- end }}
      {{- end }}
      {{- with $serviceValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceValues.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
