{{- $serviceValues := .Values.fileservice -}}
{{- if $serviceValues.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fileservice.fullname" . | quote }}
  labels:
    {{- include "fileservice.labels" . | nindent 4 }}
  {{- with $serviceValues.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
