apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph-sec.zero.fullname" . }}-headless
  namespace: {{ include "dgraph-sec.namespace" . }}
  labels:
    {{- include "dgraph-sec.labels" (dict "ctx" . "component" .Values.zero.name "extra" .Values.zero.serviceHeadless.labels) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc-zero
      port: 5080
      targetPort: 5080
  selector:
    app: {{ template "dgraph-sec.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.zero.name }}
  publishNotReadyAddresses: {{ .Values.zero.service.publishNotReadyAddresses }}
