output "secret_file" {
  value = templatefile("${path.module}/secrets.yaml.tftpl", {
    common_domain                        = var.zitadel_insecure ? "http://${var.zitadel_domain}:${var.zitadel_port}" : "https://${var.zitadel_domain}"
    fe_zitadel_client_id                 = zitadel_application_oidc.istari_frontend_service.client_id
    identity_client_integration_enabled  = var.identity_client_integration_enabled
    identity_frontend_client_id          = local.identity_frontend_client_id
    identity_frontend_redirect_uris      = join(",", local.frontend_service_redirect_uris)
    identity_generate_keys               = var.identity_generate_keys
    identity_mcp_client_id               = local.identity_mcp_client_id
    identity_mcp_client_secret           = local.identity_mcp_client_secret
    identity_mcp_enabled                 = local.identity_mcp_enabled
    identity_mcp_redirect_uris           = "https://mcp.${var.main_domain}/auth/callback"
    identity_registry_client_id          = local.identity_registry_client_id
    identity_registry_private_blob       = local.identity_registry_private_blob
    identity_registry_public_blob        = local.identity_registry_public_blob
    identity_scs_agent_private_blob      = local.identity_scs_agent_private_blob
    identity_scs_agent_public_blob       = local.identity_scs_agent_public_blob
    identity_service_base_url            = var.identity_service_base_url
    identity_signing_key_blob            = local.identity_signing_key_blob
    identity_token_encryption_key        = local.identity_token_encryption_key
    identity_service_zitadel_client_id   = zitadel_application_oidc.identity-service.client_id
    identity_service_zitadel_private_key = base64encode(zitadel_application_key.identity-service-key.key_details)
    identity_service_zitadel_manager_key = base64encode(zitadel_machine_key.identity-service-management-key.key_details)
    mcp_zitadel_client_id                = var.mcp_enabled ? zitadel_application_oidc.mcp_service_post[0].client_id : ""
    mcp_zitadel_secret                   = var.mcp_enabled ? zitadel_application_oidc.mcp_service_post[0].client_secret : ""
    rs_zitadel_client_id                 = zitadel_application_api.registry-service.client_id
    rs_zitadel_project_id                = zitadel_project.istari.id
    rs_zitadel_project_grant_id          = zitadel_project_grant.default.id
    rs_zitadel_secret                    = base64encode(zitadel_application_key.registry-service-key.key_details)
    rs_zitadel_user_manager_secret       = base64encode(zitadel_machine_key.registry-service-machine-key.key_details)
    scs_zitadel_project_grant_id         = zitadel_project_grant.default.id
    scs_zitadel_project_id               = zitadel_project.istari.id
    scs_zitadel_role_name                = zitadel_project_role.secure_connection_service_account.role_key
    scs_zitadel_user_id                  = zitadel_machine_user.secure-connection-service-user.id
    scs_zitadel_user_manager_secret      = base64encode(zitadel_machine_key.secure-connection-service-machine-key.key_details)
    zitadel_domain                       = "https://${trimsuffix(var.zitadel_domain, "/")}"
    zitadel_org_id                       = zitadel_org.default.id
  })
  sensitive = true
}
