{{- $serviceValues := .Values.docs -}}
{{- if $serviceValues.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docs.fullname" . | quote }}
  labels:
    {{- include "docs.labels" . | nindent 4 }}
  {{- with $serviceValues.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
