{{ if .Values.zero.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "istari-dgraph-sec.zero.fullname" . }}-config
  namespace: {{ include "istari-dgraph-sec.namespace" . }}
  labels:
    {{- include "istari-dgraph-sec.labels" (dict "ctx" . "component" .Values.zero.name) | nindent 4 }}
data:
  {{- with .Values.zero.configFile }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{ end }}
