{{- $serviceValues := .Values.magicDocs -}}
{{- if $serviceValues.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "magic-docs.fullname" . | quote }}
  labels:
    {{- include "magic-docs.labels" . | nindent 4 }}
  {{- with $serviceValues.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
