apiVersion: v2
name: dgraph-sec
type: application
version: 0.6.1
appVersion: v25.3.7-sec.0.2.2
description: Dgraph-sec — hardened Dgraph database for Istari platform
keywords:
- dgraph
- database
- Graph
- GraphQL
- nosql
home: https://dgraph.io/
icon: https://dgraph.io/assets/images/logo.png
maintainers:
- name: Istari Digital Infrastructure Team
  email: infra@istaridigital.com
