{{- $serviceValues := .Values.secureConnection -}}
{{- if $serviceValues.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secure-connection.fullname" . | quote }}
  labels:
    {{- include "secure-connection.labels" . | nindent 4 }}
  {{- with $serviceValues.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
