{{- if and .Values.provisioner.enabled (eq (include "provisioner.anyClientEnabled" .) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "provisioner.fullname" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
  {{- with .Values.provisioner.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
