{{- if .Values.provisioner.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "provisioner.fullname" . | quote }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
  {{- with .Values.provisioner.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
