{{- $serviceValues := .Values.identityService -}}
{{- $registrationRunAsJob := dig "identityRouterClientRegistration" "enabled" false $serviceValues -}}
{{- if $serviceValues.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity.fullname" . | quote }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
  {{- if or (dig "migrations" "runAsJob" false $serviceValues) $registrationRunAsJob $serviceValues.serviceAccountAnnotations }}
  annotations:
    {{- if or (dig "migrations" "runAsJob" false $serviceValues) $registrationRunAsJob }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    {{- end }}
    {{- with $serviceValues.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
