apiVersion: v2
name: istari-platform
description: An umbrella helm chart used to install all Kubernetes components of the Istari Digital Platform's control plane.
version: 3.20.2
appVersion: 10.x.x
type: application
maintainers:
- name: Istari Digital Infrastructure Team
  email: infra@istaridigital.com
dependencies:
- name: dgraph-sec
  version: "0.4.7"
  repository: "https://istaridigital.jfrog.io/artifactory/main-helm-local"
  condition: dgraph-sec.enabled
- name: nats
  version: "2.14.0"
  repository: "https://nats-io.github.io/k8s/helm/charts/"
  condition: nats.enabled
